In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model 
df =pd.read_csv("C://Users//halde//OneDrive//Documents//landPrices.csv")
df

area  prices
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
new_df=df.drop('prices',axis='columns')
new_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [8]:
prices=df.prices
prices

0    550000
1    565000
2    610000
3    680000
4    725000
Name: prices, dtype: int64

In [9]:
reg=linear_model.LinearRegression()
reg.fit(new_df,prices)

LinearRegression()

In [10]:
reg.predict([[3700]])

C:\Users\halde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([683030.82191781])

In [11]:
reg.predict([[5500]])

C:\Users\halde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([927448.63013699])

In [13]:
reg.coef_

array([135.78767123])

In [14]:
reg.intercept_

180616.43835616432

In [15]:
3700*135.78767123+180616.43835616432

683030.8219071643

In [17]:
area_df=pd.read_csv("C://Users//halde//OneDrive//Documents//landAreas.csv")
area_df

Area
0  1200
1  1400
2  1600
3  2000
4  2200
5  2800
6  2067
7  3955
8  3964
9  2684

In [18]:
b=reg.predict(area_df)
b

C:\Users\halde\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Area
Feature names seen at fit time, yet now missing:
- area

  warnings.warn(message, FutureWarning)


array([343561.64383562, 370719.17808219, 397876.71232877, 452191.78082192,
       479349.31506849, 560821.91780822, 461289.55479452, 717656.67808219,
       718878.76712329, 545070.54794521])

In [19]:
area_df['Prices']=b
area_df

Area         Prices
0  1200  343561.643836
1  1400  370719.178082
2  1600  397876.712329
3  2000  452191.780822
4  2200  479349.315068
5  2800  560821.917808
6  2067  461289.554795
7  3955  717656.678082
8  3964  718878.767123
9  2684  545070.547945

In [20]:
area_df.to_csv("predictPrices.csv")