In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv("C://Users//halde//OneDrive//Documents//housePrice.csv") 
df

area  bedrooms  age    price
0  2500       3.0   25  5700000
1  2800       4.0   20  5950000
2  3000       NaN   22  6200000
3  3200       3.0   30  6100000
4  3500       5.0   10  7800000
5  3900       6.0   10  8000000

In [3]:
df.bedrooms.median()

4.0

In [5]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age    price
0  2500       3.0   25  5700000
1  2800       4.0   20  5950000
2  3000       4.0   22  6200000
3  3200       3.0   30  6100000
4  3500       5.0   10  7800000
5  3900       6.0   10  8000000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [7]:
reg.coef_

array([   1612.57873244, -533124.14922825, -113869.59832037])

In [8]:
reg.intercept_

5987184.781856352

In [9]:
reg.predict([[2800,3,35]])

C:\Users\halde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4917596.843781])

In [10]:
1612.57873244*2800+ -533124.14922825*3+ -113869.59832037*35+5987184.781856352

4917596.843790652

In [11]:
reg.predict([[2200,4,5]])

C:\Users\halde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6833013.40470203])

In [12]:
1612.57873244*2200+ -533124.14922825*4+ -113869.59832037*5+5987184.781856352

6833013.404709502