In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(arr[2]+arr[3])

7


In [39]:
from numpy import random

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[4 2 5 3 1]


In [40]:
random.shuffle(arr)
print(arr)

[2 5 4 1 3]


In [30]:
x = random.rand(3,5)
print(x)

[[0.11600735 0.86425708 0.70161458 0.88637396 0.63988696]
 [0.79324564 0.09024425 0.44912702 0.68505379 0.2995546 ]
 [0.93588486 0.84108152 0.73717308 0.24665733 0.16523988]]


In [43]:
#Generate a random normal distribution of size 3x2  with mean 1 and standard deviation = 2


In [31]:
x = random.randint(100, size = (3,5))
print(x)

[[ 2 61 43 36 37]
 [97 11 79 32 35]
 [56 54 72 81  0]]


In [32]:
y = random.randint(10,30, size = (2,5))
print(y)

[[23 12 11 25 27]
 [13 24 24 24 26]]


In [35]:
x = random.choice([3,5,7,9], size = (3,5))
print(x)

[[7 9 9 3 3]
 [3 7 9 5 5]
 [3 5 5 9 9]]


In [36]:
x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0], size = (100))
print(x)

[5 7 7 7 7 7 5 3 3 3 3 7 5 7 7 7 7 5 3 3 7 7 7 3 7 7 5 7 7 3 7 7 7 7 5 7 7
 7 7 7 5 7 3 5 5 5 5 7 7 3 7 7 5 5 7 3 7 5 5 5 7 7 7 7 7 7 7 3 7 7 3 7 7 7
 7 7 3 7 5 3 7 3 5 3 7 5 5 5 5 5 5 5 7 7 7 3 7 7 7 7]


In [37]:
x = random.choice([3,5,7,9], p=[0.1,0.3,0.5,0.1], size = (3,5))
print(x)

[[3 5 7 7 5]
 [3 5 3 3 7]
 [5 7 7 7 5]]


In [34]:
arr = np.array([1,5,36,8,4,86])
arr = np.flip(np.sort([arr]))
print(arr)

[[86 36  8  5  4  1]]


In [8]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
print(np.linspace(0,23,7))

[ 0.          3.83333333  7.66666667 11.5        15.33333333 19.16666667
 23.        ]


In [13]:
zeros_array = np.zeros((2,3),dtype = np.int32)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [14]:
ones_array = np.ones((3,4),dtype = np.int32)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print('The matrix is:\n',arr)
print('The 2nd element is: ',arr[0,1])
print('The 5th element is: ',arr[0,4])

The matrix is:
 [[1 2 3 4 5]
 [4 5 6 7 8]]
The 2nd element is:  2
The 5th element is:  5


In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])
print('Matrix 1:\n',x)
print('Matrix 2:\n',y)
print('Sum is:\n',np.add(x,y))
print('Difference is:\n',np.subtract(x,y))
print('Product is:\n',np.multiply(x,y))
print('Quotient is:\n',np.divide(x,y))

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[4 5]
 [6 7]]
Sum is:
 [[ 5  7]
 [ 9 11]]
Difference is:
 [[-3 -3]
 [-3 -3]]
Product is:
 [[ 4 10]
 [18 28]]
Quotient is:
 [[0.25       0.4       ]
 [0.5        0.57142857]]


In [28]:
matrix1 = np.matrix('[4,2,5;23,55,7;45,12,77]')
print('The original matrix is:\n',matrix1)
matrix2 = matrix1.transpose()
print('The tranposed matrix is:\n',matrix2)

The original matrix is:
 [[ 4  2  5]
 [23 55  7]
 [45 12 77]]
The tranposed matrix is:
 [[ 4 23 45]
 [ 2 55 12]
 [ 5  7 77]]
